### ISSUE TITLE
create github actions to update pypi package

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift#85]
- [x] create secret in the CloudDrift account for pypitest and pypi API tokens
- [x] create a rule to build (this should work):
```
on:
  release:
    types:
      - published
  push:
    tags:
      - 'v*'
```
that triggers on new release, if the tags starts with v.
- [x] send to pypi test
- [x] send to pypi
- [x] validate that the package is properly upload to pypi on a new version released

Reference (https://github.com/OceanParcels/parcels/blob/master/.github/workflows/pypi-release.yaml)
