### ISSUE TITLE
Should docs be built and deployed on push to clouddrift/*.py files?

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#87]
As I understand it, the docs are built and deployed when there is a push to files in docs/:

https://github.com/Cloud-Drift/clouddrift/blob/17869a7b9aae8c2234746532257b22d45171b929/.github/workflows/docs.yml#L1-L7

However, docstrings are sourced from Python module files and we need a manual re-build if, say, no new module is added (no changes to docs/) but a docstring in a .py file is updated. I've been running the docs workflow manually in such cases.

Is it reasonable to also build and deploy the docs on changes to *.py files? In other words:

```yml
 name: Docs 
  
 on: 
   push: 
     branches: [ main ] 
     paths: 
       - 'docs/**' 
       - 'clouddrift/*.py'
```
